# Generated by Django 3.1.5 on 2021-01-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Nhanvien',
        ),
    ]
